# Configuration file

selected_time: none
logs_path: default
show_timestamps: true
playback_speed: 1
filter: default
spacing: false
locale: pl

replace:
  'Buty935': "&c&lB&6&lu&e&lt&a&ly&b&l9&3&l3&9&l5&f"
  '[GC2]': "&f[&9GC&b2&f]&f"
  '!Gracz!': "&a!&2Gracz&a!&f"
  '!VIP!': "&e!&6VIP&e!&f"
  '!sVIP!': "&e!&2s&6VIP&e!&f"
  '!Straznik!': "&b!&9Straznik&b!&f"
  '[HelpOp]': "&4[HelpOp]&f"
  '[SS]': "&6[SS]&f"
  'Mankai.pl': "&cMankai.pl&f"
  'jjay31': "&fjjay&93&f1&f"
  'Hey!': "&cHey!&f"
  'Nie masz ¿adnych nowych wiadomoœci.': "&6Nie masz ¿adnych nowych wiadomoœci.&f"
  'jest teraz AFK.': "&5jest teraz AFK.&f"
  'nie jest ju¿ AFK.': "&5nie jest ju¿ AFK.&f"
  '??????????': ""
  '????????': ""
  '[AreaShop]': "&2[AreaShop]&f"
  '?Sensei?': "*&4Sensei&f*"
  '?Pomocnik?': "*&bPomocnik&f*"
  '!Tutor!': "&a!&2Tutor&a!&f"
  'zbanowa³': "&czbanowa³&f"
  'wyrzuci³ gracza': "&cwyrzuci³ gracza&f"
  '-> Ja]': "&6-> &cJa&6]&f"
  '[NO-LIFE]': "&8[NO-&aLIFE&8]&f"
  '[KLOCUSZEK]': "&8[KLOCUSZEK]&f"
  '[KSI¥¯Ê]': "&8[KSI&b¥&8¯Ê]&f"
  '[TYPOWY]': "&6[&eTYPOWY&6]&f"
  '[RAK]': "&c[RAK]&f"